---
title: "Real World Manuscript Analyses"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_opatient_idions: 
  chunk_output_type: console
---

<style type= "text/css">

.## Figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

## Table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opatient_ids_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
opatient_idions(gtsummary.print_engine = "gt")
opatient_idions(gtsummary.as_gt.addl_cmds = "gt::tab_opatient_idions(table.font.size = 14, data_row.padding = gt::px(1))")
```

```{r library}
library(tidyverse)
library(ggplot2)
library(gtsummary)
library(labelled)
library(DescTools)
library(patchwork)
library(ggbreak)
library(survival)
library(survminer)
```

```{r load}
# path <- fs::path("","Volumes","Peres_Research", "Myeloma", "Cytopenias")

MM_cart <-
  readxl::read_xlsx("./Data ASCO 2022 Myeloma CAR-T SOC Outcomes 04072022.xlsx",
                    skip = 1, n_max = 200
                    ) %>% 
  rename(patient_id = `PT Identifier (DO NOT USE PHI)`)
```




```{r data cleaning}
cart <- MM_cart %>% 
  # Exclude patients who had manufacturing cart failure or died prior cart infusion
  filter(is.na(exclude_for_manufacturing_cart_failure_or_died_prior_cart_infusion)) %>% 
  # Keep seconf infusion date for patients who had failure
  # mutate(`Date of Apheresis (or # of days from apheresis to LD)` = as.character(`Date of Apheresis (or # of days from apheresis to LD)`))


  separate(`Date of Apheresis (or # of days from apheresis to LD)`, 
           into= c("first_date_of_apheresis", "date_of_apheresis"), sep = ", 2nd-|; 2nd - ", remove = FALSE) %>% 
  mutate(first_date_of_apheresis = str_remove(first_date_of_apheresis, "1st - |1st-"),
         first_date_of_apheresis = as.Date(as.numeric(first_date_of_apheresis), 
                                             origin = "1899-12-30"),
         date_of_apheresis = as.Date(date_of_apheresis, format = "%m/%d/%Y"),
         date_of_apheresis = coalesce(date_of_apheresis, first_date_of_apheresis)
         ) %>% 
  select(-first_date_of_apheresis)
  
```

