---
title: "Talq Teclistamab analyses"
author: "Christelle Colin-Leitzinger"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options:
  chunk_output_type: console
---

<style type= "text/css">

. figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{=html}
<style type= "text/css">

. figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

```{r library}
library(tidyverse)
library(ggplot2)
library(gtsummary)
library(labelled)
library(patchwork)
library(survival)
library(survminer)
theme_set(theme_classic())
theme_gtsummary_compact()
```

```{r load}
# path <- fs::path("","Volumes","Peres_Research", "Myeloma", "Analyses", "Janssen Teclistamab")

data <- 
  readxl::read_xlsx(
    paste0(#path, 
      here::here(), "/data/2026_analysis",
      "/JnJ_Tec_Talq_Dataset_PHI.xlsx"),
    na = c("N/A", " ", "", "NA") # "." to fix the weird encoding with non-breaking space
  ) %>% 
  `colnames<-`(str_replace(colnames(.), "^#Infection_", "infection_type_")) %>% 
  janitor::clean_names()

data <- data %>% 
  rename(date_of_infection_1 = date_of_infection_109,
         infection_severity_1 = infection_severity_severe_hospitalization_or_requiring_iv_antibiotics_108,
         date_of_infection_2 = date_of_infection_112,
         infection_severity_2 = infection_severity_severe_hospitalization_or_requiring_iv_antibiotics_111,
         date_of_infection_3 = date_of_infection_115,
         infection_severity_3 = infection_severity_severe_hospitalization_or_requiring_iv_antibiotics_114,
         date_of_infection_4 = date_of_infection_118,
         infection_severity_4 = infection_severity_severe_hospitalization_or_requiring_iv_antibiotics_117,
         inpatient_length_of_hospital_stay_days = 
           if_inpatient_length_of_hospital_stay_total_days_including_all_admissions_0_if_done_outpt_with_no_admissions
         ) %>% 
  `colnames<-`(str_remove_all(colnames(.), "_bacterial_viral_fungal"))
```

```{r exploratory function}
check_data <- function(data){

  for(i in 1:length(colnames(data))) {

    # if(class(data[[i]]) == "factor" | class(data[[i]]) == "character") {

      # print(data[i])
      print(colnames(data[i]))
      print(str(data[i]))
      print(table(data[[i]]))
    # }

  }
}

check_data(data[4:178])
```

```{r temp_fix}
# temp_fix <- data1 %>%
# #   mutate(baseline_crp_prior_to_bs_ab_initiation_mg_l = case_when(
# #     baseline_crp_prior_to_bs_ab_initiation_mg_l == "4.4."        ~ 4.4,
# #     TRUE                  ~ as.numeric(baseline_crp_prior_to_bs_ab_initiation_mg_l)
# #   )) %>% 
# #   mutate(alc_day_15 = case_when(
# #     alc_day_15 == "85-"   ~ 85,
# #     TRUE                  ~ as.numeric(alc_day_15)
# #   )) %>% 
# #   mutate_at(c(   ############################### Remove when fix temp un necessary
# #               "max_crp"
# #   ), ~ as.numeric(.)
# #   )
#   mutate(prior_auto_sct_no_0_yes_1 = case_when(
#     prior_auto_sct_no_0_yes_1 == 9          ~ NA_real_,
#     TRUE                                    ~ prior_auto_sct_no_0_yes_1
#   )) %>% 
#   mutate(most_recent_bcma_agent_name = case_when(
#     most_recent_bcma_agent_name == "Carvylti" ~ "Carvykti",
#     TRUE                                      ~ most_recent_bcma_agent_name
#   ))
```


```{r fix name date and recode 012etc}
data1 <- data %>% 
  # General----
  # Fix letter case and missing
  # mutate(across(where(is.character), ~ str_replace(., "NE|ND|N/A|Not done", NA_character_))) %>%
  mutate(across(c(where(is.character),
                  -c("patient_identifier",
                     "myeloma_involved_heavy_chain_ig_g_ig_a_ig_m_ig_d_ig_e_or_blank",
                     "specific_debulking_therapy_used_prior_to_bs_ab"
                     # "best_documented_emd_response"
                     )),
                ~ str_to_sentence(.) )) %>%
  mutate(across(c(contains("vgpr") #"response_to_bridging_chemotherapy"
                  ),
                ~ str_to_upper(.) )) %>%
  # Recode Y/N
  mutate_at(c("tal_specifically_designed_as_pre_car_t_holding_or_bridging_y_n"
  ), 
  ~ case_when(
    . == "Y"                                              ~ "Yes",
    . == "N"                                              ~ "No",
    TRUE                                                ~ as.character(.)
  )) %>% 
  # Recode 0/1
  mutate_at(c("prophylactic_tocilizumab_n_0_y_1",
              "cerebellar_toxicity_or_ataxia_if_so_describe",
              "infection_n_0_y_1", 
              "infection_severity_1", "infection_severity_2",
              "infection_severity_3", "infection_severity_4",
              "recurrent_crs_n_0_y_1",
              "tocilizumab_as_tx_n_0_y_1", "steroid_use_as_tx_n_0_y_1", "anakinra_n_0_y_1",
              "bs_ab_combined_at_any_point_such_as_with_pom_dara_or_other_bs_ab_no_0_yes_1",
              "bs_ab_served_only_as_pre_car_t_bridging_0_no_1_yes",
              "oligo_or_non_secretory_at_bs_ab_initiation_0_no_1_yes",
              "deletion_17p_prior_to_bs_ab_0_no_1_yes", "t_4_14_prior_to_bs_ab_0_no_1_yes", 
              "t_11_14_prior_to_bs_ab_0_no_1_yes", "t_14_16_prior_to_bs_ab_0_no_1_yes", 
              "gain_amp1q21_prior_to_bs_ab_0_no_1_yes", "amp_1_q_only_0_no_1_yes",
              "deletion_1p_0_no_1_yes",
              "prior_auto_sct_no_0_yes_1",
              "prior_bcma_directed_therapy_no_0_y_1",
              "prior_cart_0_no_1_yes",
              "triple_class_refractory_i_mi_d_pi_anti_cd38_no_0_y_1",
              "penta_refractory_2_p_is_2_i_mi_ds_anti_cd38_no_0_y_1",
              "debulking_therapy_prior_to_bs_ab_no_0_y_1",
              "did_patient_receive_xrt_in_combination_with_bs_ab_no_0_yes_1",
              "h_o_plasma_cell_leukemia_no_0_yes_1",
              "eligible_for_corresponding_bs_ab_trial_on_first_dose_use_trial_elig_sheet_to_help_you_no_0_y_1",
              "step_up_initiated_inpatient_or_outpatient",
              "hemodialysis_pre_bs_ab_y_1_n_0",
              "icu_admission_during_first_cycle_n_0_y_1",
              "need_for_gcsf", "need_for_tpo_agonist",
              "ivig_n_0_y_1",
              
              
              # "active_pcl_5_percent_cp_cs_within_30_days_prior_or_after_bs_ab_initiation_0_no_1_yes",
              # "high_marrow_burden_50_percent_p_cs_if_checked_within_30_days_before_bs_ab_initiation_n_0_y_1",
              # "hemodialysis_post_bs_ab_y_1_n_0",
              # "modification_in_schedule_to_monthly_0_no_1_yes"
  ), 
  ~ case_when(
    . == 0                                              ~ "No",
    . == 1                                              ~ "Yes",
    TRUE                                                ~ as.character(.)
  )) %>% 
  mutate(bs_ab_name_tec_1_tal_2_elra_3_linvo_4 = case_when(
    bs_ab_name_tec_1_tal_2_elra_3_linvo_4 == 1          ~ "Teclistamab",
    bs_ab_name_tec_1_tal_2_elra_3_linvo_4 == 2          ~ "Talquetamab",
    bs_ab_name_tec_1_tal_2_elra_3_linvo_4 == 3          ~ "Elra",
    bs_ab_name_tec_1_tal_2_elra_3_linvo_4 == 4          ~ "Linvo",
    TRUE                                                ~ NA_character_
  )) %>% 
  mutate(bs_ab_sud_inpatient_0_bs_ab_sup_outpatient_1 = case_when(
    bs_ab_sud_inpatient_0_bs_ab_sup_outpatient_1 == 0   ~ "Inpatient",
    bs_ab_sud_inpatient_0_bs_ab_sup_outpatient_1 == 1   ~ "Outpatient"
  )) |> 



  mutate(reason_no_date_of_first_bs_ab_full_dose = case_when(
    str_detect(date_of_first_bs_ab_full_dose, "([A-Za-z]+)")     ~ date_of_first_bs_ab_full_dose
  ), .after = date_of_first_bs_ab_full_dose) |> 
  # mutate(was_discontinued = case_when(
  #   date_of_disocntinuation_if_cotinues_enter_0 == 0     ~ "Continued",
  #   !is.na(date_of_disocntinuation_if_cotinues_enter_0)  ~ "Discontinued"
  # ), .after = ) %>%
  # Dates
  mutate(across(c(#"date_of_mm_diagnosis",
                  # "date_of_bs_ab_step_up_d1",
                  "date_of_first_bs_ab_full_dose",
                  # "date_of_max_ferritin",
                  # "date_of_max_crp",
                  # "date_of_onset_of_crs",
                  "date_of_max_crs",
                  # "date_of_onset_of_icans",
                  # "date_of_max_ican",
                  # "date_of_infection_1st",
                  # "date_of_infection_2nd",
                  # "date_of_infection_3rd",
                  # "date_of_infection_4th",
                  # "anc_nadir_date", "hgb_nadir_date",
                  # "plt_nadir_date", "date_of_ig_g_nadir",
                  # "date_of_first_ivig_dose_following_bs_ab_administration",
                  # "date_of_best_mrd_response_relative_to_bs_ab_start",
                  # "date_of_pd",
                  "date_of_discontinuation_if_continues_enter_0_bs_ab_stop_date"
                  # "date_of_death", "date_of_last_contact",
                  # "date_of_first_exposure_to_prior_bcma_agent",
                  # "date_of_last_exposure_to_prior_bcma_agent",
                  # "date_last_exposure",
                  # "while_on_bs_ab_date_of_first_documented_emd_response",
                  # "date_of_best_documented_emd_response",
                  # "date_of_last_imaging_before_data_cutoff_only_in_pts_who_are_still_responding"
                  ),
                ~ as.Date(as.numeric(.), 
                          # tryFormats = c("%m/%d/%y", "%m/%d/%Y"), 
                          origin = "1899-12-30")))





#   
#   
#   mutate(type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3 = case_when(
#     type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3 == 1        ~ "ADC",
#     type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3 == 2        ~ "CART",
#     type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3 == 3        ~ "BsAb",
#     TRUE                                      ~ as.character(type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3)
#   )) %>% 
#   
#   mutate(response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 = case_when(
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 1        ~ "CR",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 2        ~ "VGPR",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 3        ~ "PR",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 4        ~ "SD",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 5        ~ "PD",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 6        ~ "NE",
#     TRUE                                      ~ as.character(response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6)
#   )) %>% 
#   mutate(response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 = case_when(
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == "CR"     ~ "PR or better ",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == "VGPR"   ~ "PR or better ",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == "PR"     ~ "PR or better ",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == "SD"     ~ "SD/PD",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == "PD"     ~ "SD/PD",
#     response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == "NE"     ~ "NE",
#     TRUE                                      ~ as.character(response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6)
#   )) %>% 
#   
#   


#   mutate(total_number_true_emd_plasmacytomas_if_1_2_sites_write_1_or_2_if_2_plasmacytomas_just_write_3 = case_when(
#     total_number_true_emd_plasmacytomas_if_1_2_sites_write_1_or_2_if_2_plasmacytomas_just_write_3 == 1        ~ "1 site",
#     total_number_true_emd_plasmacytomas_if_1_2_sites_write_1_or_2_if_2_plasmacytomas_just_write_3 == 2        ~ "2 sites",
#     total_number_true_emd_plasmacytomas_if_1_2_sites_write_1_or_2_if_2_plasmacytomas_just_write_3 == 3        ~ ">2 sites",
#     TRUE                                      ~ as.character(total_number_true_emd_plasmacytomas_if_1_2_sites_write_1_or_2_if_2_plasmacytomas_just_write_3)
#   )) %>% 
#   
#   
#   
#   mutate(xrt_2_weeks_before_and_after_3_months_of_bs_ab_starting_yes_no_response = case_when(
#     xrt_2_weeks_before_and_after_3_months_of_bs_ab_starting_yes_no_response == "N"         ~ "No",
#     TRUE                                      ~ xrt_2_weeks_before_and_after_3_months_of_bs_ab_starting_yes_no_response
#   )) %>%
#   mutate(true_emd_relapse_yes_no = case_when(
#     true_emd_relapse_yes_no == "Y"         ~ "Yes",
#     is.na(true_emd_relapse_yes_no)         ~ NA_character_,
#     TRUE                                   ~ as.character(true_emd_relapse_yes_no)
#   )) %>% 
#   
#   
#   
#   mutate(if_yes_what_location_0_same_site_1_new_site_2_both = case_when(
#     if_yes_what_location_0_same_site_1_new_site_2_both == 0        ~ "Same site",
#     if_yes_what_location_0_same_site_1_new_site_2_both == 1        ~ "New site",
#     if_yes_what_location_0_same_site_1_new_site_2_both == 2        ~ "Both",
#     TRUE                                      ~ as.character(if_yes_what_location_0_same_site_1_new_site_2_both)
#   ))
#   
# 
# 


```

```{r}
data2 <- data1 %>% 
  # Age categories----
  mutate(agecat = case_when(
    age_at_bs_ab_initiation < 70                                         ~ "< 70 years",
    age_at_bs_ab_initiation >= 70                                        ~ "≥ 70 years"
  ),
  agecat = factor(agecat, levels = c("< 70 years", "≥ 70 years")),
  .after = age_at_bs_ab_initiation
  ) %>%
  mutate(year_bsab = year(date_of_bs_ab_step_up_d1)) %>%
  # Sex categories----
  mutate(sex_0_male_1_female = case_when(
    sex_0_male_1_female == 0                  ~ "Male",
    sex_0_male_1_female == 1                  ~ "Female",
    TRUE                                      ~ as.character(sex_0_male_1_female)
  )) %>%
  mutate(male_sex = case_when(
    sex_0_male_1_female == "Male"                                    ~ 1,
    sex_0_male_1_female == "Female"                                  ~ 0
  ), .after = sex_0_male_1_female) %>%
  # Race eth
  rename_at(vars(contains("race")), ~ "race") %>%
  rename_at(vars(contains("hispanic")), ~ "ethnicity") %>%
  mutate(race = case_when(
    race == 0                                 ~ "White",
    race == 1                                 ~ "Black",
    race == 2                                 ~ "Asian American and Pacific Islander",
    race == 3                                 ~ "American_indian",
    race == 4                                 ~ "Other",
    race == 5                                 ~ "Unknown",
    TRUE                                      ~ as.character(race)
  )) %>%
  mutate(ethnicity = case_when(
    ethnicity == 0                            ~ "Non-Hispanic",
    ethnicity == 1                            ~ "Hispanic",
    TRUE                                      ~ as.character(ethnicity)
  )) %>%
  mutate(raceeth = case_when(
    ethnicity == "Hispanic"                   ~ "Hispanic, any races",
    race == "White" &
      ethnicity == "Non-Hispanic"             ~ "White, Non-Hispanic",
    race == "Black" &
      ethnicity == "Non-Hispanic"             ~ "Black, Non-Hispanic",
    !is.na(race) &
      ethnicity == "Non-Hispanic"             ~ "Other, Non-Hispanic",
    TRUE                                      ~ race
  )) %>%
  # ECOG
  mutate_at(c("ecog_ps_at_bs_ab_initiation_0_5"), 
            ~ factor(.)
  ) %>%
  mutate(ecog_ps_at_bs_ab_initiation_0_5_cat = case_when(
    ecog_ps_at_bs_ab_initiation_0_5 == 0 |
      ecog_ps_at_bs_ab_initiation_0_5 == 1                                ~ "0-1",
    ecog_ps_at_bs_ab_initiation_0_5 %in% c(2:5)                           ~ "2-5"
  )) %>%
  # Myeloma
  rename(true_emd_prior_bsab_type = just_prior_to_bs_ab_initiation_is_there_true_emd_0_none_1_paraskeletal_only_2_true_emd_paraskeletal) |> 
  mutate(true_emd_prior_bsab_type = case_when(
    true_emd_prior_bsab_type == 0        ~ "None",
    true_emd_prior_bsab_type == 1        ~ "Paraskeletal only",
    true_emd_prior_bsab_type == 2        ~ "True EMD (+/-paraskeletal)",
    TRUE                                      ~ as.character(true_emd_prior_bsab_type)
  )) %>%
  mutate(true_emd_prior_bsab = case_when(
    true_emd_prior_bsab_type == "True EMD (+/-paraskeletal)"     ~ "Yes",
    true_emd_prior_bsab_type == "Paraskeletal only"              ~ "No",
    true_emd_prior_bsab_type == "None"                           ~ "No"
  )) %>%



  mutate(subtype = case_when(
    oligo_or_non_secretory_at_bs_ab_initiation_0_no_1_yes == "Yes"               ~ "Oligo/non-secretory",
    !is.na(myeloma_involved_heavy_chain_ig_g_ig_a_ig_m_ig_d_ig_e_or_blank) &
      !is.na(myeloma_involved_light_chain_kappa_lambda_biclonal_blank)           ~ "Intact immunoglobulin (Heavy + Light)",
    is.na(myeloma_involved_heavy_chain_ig_g_ig_a_ig_m_ig_d_ig_e_or_blank) &
     !is.na(myeloma_involved_light_chain_kappa_lambda_biclonal_blank)            ~ "Light chain only",
    TRUE           ~ paste(oligo_or_non_secretory_at_bs_ab_initiation_0_no_1_yes,
                           myeloma_involved_light_chain_kappa_lambda_biclonal_blank,
                           myeloma_involved_heavy_chain_ig_g_ig_a_ig_m_ig_d_ig_e_or_blank)
  )) %>%
  # Cytogenetics ----
  mutate(cytogenetics = case_when(
    deletion_17p_prior_to_bs_ab_0_no_1_yes == "Yes" |
      t_4_14_prior_to_bs_ab_0_no_1_yes == "Yes" |
      t_14_16_prior_to_bs_ab_0_no_1_yes == "Yes"                     ~ "Yes",
    deletion_17p_prior_to_bs_ab_0_no_1_yes == "No" &
      t_4_14_prior_to_bs_ab_0_no_1_yes == "No" &
      t_14_16_prior_to_bs_ab_0_no_1_yes == "No"                      ~ "No",
    TRUE                                                             ~ NA_character_
  ), .before = deletion_17p_prior_to_bs_ab_0_no_1_yes) %>%
  mutate(high_risk_cyto_newdef = case_when(
    deletion_17p_prior_to_bs_ab_0_no_1_yes == "Yes"                  ~ "Yes",
    t_4_14_prior_to_bs_ab_0_no_1_yes == "Yes" & 
      gain_amp1q21_prior_to_bs_ab_0_no_1_yes == "Yes"                              ~ "Yes",
    t_14_16_prior_to_bs_ab_0_no_1_yes == "Yes" & 
      gain_amp1q21_prior_to_bs_ab_0_no_1_yes == "Yes"                              ~ "Yes",
    t_4_14_prior_to_bs_ab_0_no_1_yes == "Yes" & 
      deletion_1p_0_no_1_yes == "Yes"                               ~ "Yes",
    t_14_16_prior_to_bs_ab_0_no_1_yes == "Yes" & 
      deletion_1p_0_no_1_yes == "Yes"                               ~ "Yes",
    gain_amp1q21_prior_to_bs_ab_0_no_1_yes == "Yes" & 
      deletion_1p_0_no_1_yes == "Yes"                               ~ "Yes",
    is.na(deletion_17p_prior_to_bs_ab_0_no_1_yes) | 
      is.na(t_4_14_prior_to_bs_ab_0_no_1_yes) | 
      is.na(t_14_16_prior_to_bs_ab_0_no_1_yes) | 
      is.na(gain_amp1q21_prior_to_bs_ab_0_no_1_yes) | 
      is.na(deletion_1p_0_no_1_yes)                                 ~ NA_character_, 
    TRUE                                                             ~ "No"
  ))
  # mutate(pcl_5_percent_cp_cs_at_any_point_from_dx_through_last_pre_bs_ab_lo_t_0_no_1_secondary_pcl_not_at_dx_2_primary_pcl_at_dx = case_when(
  #   pcl_5_percent_cp_cs_at_any_point_from_dx_through_last_pre_bs_ab_lo_t_0_no_1_secondary_pcl_not_at_dx_2_primary_pcl_at_dx == 0        ~ "No",
  #   pcl_5_percent_cp_cs_at_any_point_from_dx_through_last_pre_bs_ab_lo_t_0_no_1_secondary_pcl_not_at_dx_2_primary_pcl_at_dx == 1        ~ "Secondary PCL (not at Dx)",
  #   pcl_5_percent_cp_cs_at_any_point_from_dx_through_last_pre_bs_ab_lo_t_0_no_1_secondary_pcl_not_at_dx_2_primary_pcl_at_dx == 2        ~ "Primary PCL (at Dx)",
  #   TRUE                                      ~ as.character(pcl_5_percent_cp_cs_at_any_point_from_dx_through_last_pre_bs_ab_lo_t_0_no_1_secondary_pcl_not_at_dx_2_primary_pcl_at_dx)
  # )) %>%
```


```{r treatment}
data3 <- data2 %>% 
  mutate(number_of_prior_lines_of_therapy_before_bs_ab_cat = case_when(
    number_of_prior_lines_of_therapy_before_bs_ab <= 4                        ~ "≤ 4",
    number_of_prior_lines_of_therapy_before_bs_ab > 4                         ~ "> 4"
  ), .after = number_of_prior_lines_of_therapy_before_bs_ab) %>%  
  # Refractory status ----
  mutate_at(c("bortezomib_status_exposed_0_vs_refractory_1_vs_naive_2",
              "carfilzomib_status_exposed_0_vs_refractory_1_vs_naive_2",
              "lenalidomide_status_exposed_0_vs_refractory_1_vs_naive_2",
              "pomalidomide_status_exposed_0_vs_refractory_1_vs_naive_2",
              "daratumumab_or_isatuximab_status_exposed_0_vs_refractory_1_vs_naive_2"
  ),
  ~ case_when(
    . == 0                                              ~ "Not refractory",
    . == 1                                              ~ "Refractory",
    . == 2                                              ~ "Not refractory",
    TRUE                                                ~ NA_character_
  )) %>%
  mutate(immuno = case_when(
    lenalidomide_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory" |
      pomalidomide_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory"           ~ "Yes",
    lenalidomide_status_exposed_0_vs_refractory_1_vs_naive_2 != "Refractory" |
      pomalidomide_status_exposed_0_vs_refractory_1_vs_naive_2 != "Refractory"           ~ "No"
  ), .after = pomalidomide_status_exposed_0_vs_refractory_1_vs_naive_2) %>% 
  mutate(proteasome = case_when(
    bortezomib_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory" |
      carfilzomib_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory"            ~ "Yes",
    bortezomib_status_exposed_0_vs_refractory_1_vs_naive_2 != "Refractory" |
      carfilzomib_status_exposed_0_vs_refractory_1_vs_naive_2 != "Refractory"            ~ "No"
  ), .after = immuno) %>%
  mutate(dara = case_when(
    daratumumab_or_isatuximab_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory"            ~ "Yes",
    is.na(daratumumab_or_isatuximab_status_exposed_0_vs_refractory_1_vs_naive_2)            ~ NA_character_,
    TRUE                                                           ~ "No"
  ), .after = daratumumab_or_isatuximab_status_exposed_0_vs_refractory_1_vs_naive_2) %>%
  mutate(doubleref = case_when(
    proteasome == "Yes" &
      immuno == "Yes"                                              ~ "Yes",
    TRUE                                                           ~ "No"
  ), .after = proteasome) %>%
  mutate(tripleref = case_when(
    proteasome == "Yes" &
      immuno == "Yes" &
      dara == "Yes"          ~ "Yes",
    TRUE                                                           ~ "No"
  )) %>% 
  mutate(pentaref = case_when(
    bortezomib_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory" & 
      carfilzomib_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory" &
      lenalidomide_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory" & 
      pomalidomide_status_exposed_0_vs_refractory_1_vs_naive_2 == "Refractory" & 
      dara == "Yes"          ~ "Yes",
    TRUE                                                           ~ "No"
  )) |> 
  mutate(type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3 = case_when(
    type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3 == 1    ~ "ADC",
    type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3 == 2    ~ "CART",
    type_of_most_recent_bcma_agent_adc_1_cart_2_bs_ab_3 == 3    ~ "BsAb"
  )) |> 
  mutate(response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 = case_when(
    response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == "sCR" ~ "sCR",
    response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 1     ~ "CR",
    response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 2     ~ "VGPR",
    response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 3     ~ "PR",
    response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 4     ~ "SD",
    response_to_most_recent_bmca_agent_cr_1_vgpr_2_pr_3_sd_4_pd_5_ne_6 == 5     ~ "PD",
  )) |> 
  mutate(days_of_icu_admission_calculated = case_when(
    inpatient_length_of_hospital_stay_days == 0                        ~ NA_real_,
    TRUE                                                            ~ inpatient_length_of_hospital_stay_days
  ))
  
  
  
  
  
  
  

  # 
  # # Plasma cell----
  # mutate(is_percent_cp_cs_checked_within_30_days_before_bs_ab_initiation = case_when(
  #   percent_cp_cs_if_pb_checked_within_30_days_before_bs_ab_initiation == 0       ~ "0 = Not checked?",
  #   !is.na(percent_cp_cs_if_pb_checked_within_30_days_before_bs_ab_initiation)    ~ "not 0 = Checked?"
  # )) %>% 
  # mutate(percent_cp_cs_if_pb_checked_within_30_days_before_bs_ab_initiation = case_when(
  #   percent_cp_cs_if_pb_checked_within_30_days_before_bs_ab_initiation == 0       ~ NA_real_,
  #   !is.na(percent_cp_cs_if_pb_checked_within_30_days_before_bs_ab_initiation)   
  #   ~ percent_cp_cs_if_pb_checked_within_30_days_before_bs_ab_initiation
  # ))
  # 
```

```{r baseline}
data4 <- data3
# Fix the "<" and ">" to take the min or max or each column including numbers next to the signs----
# Also replace "Suboptimal" by NA
vec_col <- c("baseline_ig_g_prior_to_bs_ab_initiation_mg_d_l"
             #"baseline_ig_g_prior_to_bs_ab_initiation_mg_d_l"
             )
class(data4) <- "data.frame"

for (i in vec_col) {

  if (class(data4[, i]) == "character") {

    data4 <- data4 %>%
      mutate(wo_sign = as.numeric(str_remove(data4[, i], ">|<"))) %>%
      mutate(!!i := case_when(
        str_detect(data4[, i], ">")                 ~ max(wo_sign, na.rm = TRUE),
        str_detect(data4[, i], "<")                 ~ min(wo_sign, na.rm = TRUE),
        TRUE                                         ~ as.numeric(wo_sign)
      )) %>%
      select(-c(wo_sign))
  }
}
```


```{r toxicities}
cart5 <- data4 %>% 
# CRS ----
  mutate(crs_any = ifelse(max_crs_grade_0_5 == 0, "No", "Yes"),
       crs_any2 = ifelse(crs_any == "No", 0, 1),
       crs_gradecat2 = case_when(
         max_crs_grade_0_5 == 0                        ~ "No CRS",
         max_crs_grade_0_5 == 1                        ~ "Grade 1",
         max_crs_grade_0_5 >= 2                        ~ "Grade 2+"),
       crs_gradecat2 = factor(crs_gradecat2, levels = c("No CRS", "Grade 1", "Grade 2+")),
       crs_gradecat3 = case_when(
         max_crs_grade_0_5 == 0                        ~ "No CRS",
         max_crs_grade_0_5 %in% c(1:2)                 ~ "Grade 1 or 2",
         max_crs_grade_0_5 >= 3                        ~ "Grade 3+"),
       crs_gradecat3 = factor(crs_gradecat3, levels = c("No CRS", "Grade 1 or 2", "Grade 3+"))
  ) %>%
  mutate(gr3_CRS = case_when(
    max_crs_grade_0_5 %in% c(1:2)                      ~ "Grade <3",
    max_crs_grade_0_5 %in% c(3:5)                      ~ "Grade ≥3"
  )) %>%
  mutate(gr2_CRS = case_when(
    max_crs_grade_0_5 %in% c(1)                        ~ "Grade <2",
    max_crs_grade_0_5 %in% c(2:5)                      ~ "Grade ≥2"
  )) %>%
  mutate(day_of_onset_crs_relative_to_initiation =
           interval(start = date_of_bs_ab_step_up_d1, end = date_of_onset_of_crs) /
           duration(n =1, unit = "days")
  ) %>%
  mutate(day_of_max_crs_relative_to_initiation =
           interval(start = date_of_bs_ab_step_up_d1, end = date_of_max_crs) /
           duration(n =1, unit = "days")
  ) %>%
  # ICANS ----
  mutate(icans_any = ifelse(max_icans_grade == 0, "No", "Yes"),
       icans_any2 = ifelse(icans_any == "No", 0, 1),
       icans_gradecat2 = case_when(
         max_icans_grade == 0                      ~ "No ICANS",
         max_icans_grade == 1                      ~ "Grade 1",
         max_icans_grade >= 2                      ~ "Grade 2+"),
       icans_gradecat2 = factor(icans_gradecat2, levels = c("No ICANS", "Grade 1", "Grade 2+")),
       icans_gradecat3 = case_when(
         max_icans_grade == 0                      ~ "No ICANS",
         max_icans_grade %in% c(1:2)               ~ "Grade 1 or 2",
         max_icans_grade >= 3                      ~ "Grade 3+"),
       icans_gradecat3 = factor(icans_gradecat3, levels = c("No ICANS", "Grade 1 or 2", "Grade 3+")),
       gr3_ICANS = case_when(
         max_icans_grade %in% c(1:2)               ~ "Grade <3",
         max_icans_grade %in% c(3:5)               ~ "Grade ≥3"
       )) %>%
  mutate(gr2_ICANS = case_when(
    max_icans_grade %in% c(1)                      ~ "Grade <2",
    max_icans_grade %in% c(2:5)                    ~ "Grade ≥2"
  )) |> 
  mutate(day_of_onset_icans_relative_to_initiation =
           interval(start = date_of_bs_ab_step_up_d1, end = date_of_onset_of_icans) /
           duration(n =1, unit = "days")
  ) %>%
  mutate(day_of_max_icans_grade_relative_to_initiation =
           interval(start = date_of_bs_ab_step_up_d1, end = date_of_max_ican) /
           duration(n =1, unit = "days")
  ) |> 
  
  

  # mutate(treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain = str_replace(
  #   treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain,
  #   "1", "Infection")) %>%
  # mutate(treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain = str_replace(
  #   treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain,
  #   "2", "Cytopenias")) %>%
  # mutate(treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain = str_replace(
  #   treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain,
  #   "3", "CRS")) %>%
  # mutate(treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain = str_replace(
  #   treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain,
  #   "4", "ICANS")) %>%
  # mutate(treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain = str_replace(
  #   treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain,
  #   "5", "Other")) %>%
  # mutate(treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain = case_when(
  # treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain == 1        ~ "Infection",
  # treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain == 2        ~ "Cytopenias",
  # treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain == 3        ~ "CRS",
  # treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain == 4        ~ "ICANS",
  # treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain == 5        ~ "Other",
  #   TRUE                                      ~ treatment_delays_during_first_cycle_no_delays_0_infection_1_cytopenias_2_crs_3_icans_4_other_5_explain
  # )) %>%
  mutate(ivig_n_0_y_1 = case_when(
    str_detect(ivig_n_0_y_1, "0")       ~ "No",
    str_detect(ivig_n_0_y_1, "1")       ~ "Yes"
  )) |> 
  mutate(ivig_given_regardless_of_ig_g_levels_0_or_ivig_given_in_response_to_low_ig_g_levels_1 = case_when(
    ivig_given_regardless_of_ig_g_levels_0_or_ivig_given_in_response_to_low_ig_g_levels_1 == 0      ~ "given_regardless_of_ig_g_levels",
    ivig_given_regardless_of_ig_g_levels_0_or_ivig_given_in_response_to_low_ig_g_levels_1 == 1      ~ "given_in_response_to_low_ig_g_levels"
  ))


```

```{r survival}
cart3 <- cart5 %>% 
  # pfs
  mutate(pfs_event = case_when(
    !is.na(date_of_pd) | !is.na(date_of_death)         ~ 1,
    TRUE                                               ~ 0
  ), .after = progression_yes_no) %>%
  mutate(pfs_date = coalesce(date_of_pd, date_of_death, date_of_last_contact),
         .after = death_yes_no) %>%
  mutate(pfs_time_from_initiation_months =
           interval(
             start = date_of_bs_ab_step_up_d1,
             end = pfs_date)/
           duration(n=1, units = "months"),
         .after = death_yes_no) %>%
  # os
  mutate(os_event = case_when(
    !is.na(date_of_death)                              ~ 1,
    TRUE                                               ~ 0
  ),
  .after = death_yes_no) %>%
  mutate(os_date = coalesce(date_of_death, date_of_last_contact),
         .after = death_yes_no) %>%
  mutate(os_time_from_initiation_months =
           interval(
             start = date_of_bs_ab_step_up_d1,
             end = os_date)/
           duration(n=1, units = "months"),
         .after = death_yes_no) %>%


  mutate(time_from_MM_to_tec_days =
           interval(start = date_of_mm_diagnosis, end = date_of_bs_ab_step_up_d1) /
           duration(n =1, unit = "days")
  ) %>%

  mutate(tec_end_date = coalesce(date_of_disocntinuation_if_cotinues_enter_0, pfs_date)
  ) %>%
  mutate(duration_of_tec_days =
           interval(start = date_of_bs_ab_step_up_d1, end = tec_end_date) /
           duration(n =1, unit = "days")
  ) %>%
  mutate(tec_event = case_when(
    discontinuation_yes_no == "Yes"           ~ 1,
    pfs_event == 1                            ~ 1,
    discontinuation_yes_no == "No" &
      pfs_event == 0                          ~ 0
  )) %>%
  # mutate(duration_of_tec_days_cat = case_when(
  #   duration_of_tec_days <= median(duration_of_tec_days)               ~ "Low",
  #   duration_of_tec_days > median(duration_of_tec_days)                ~ "High"
  # )) %>%
  #   
#   
  mutate(reason_for_discontinuation_pd_1_toxicity_2_ongoing_response_3_death_4_other_5_explain = case_when(
    reason_for_discontinuation_pd_1_toxicity_2_ongoing_response_3_death_4_other_5_explain == 1        ~ "PD",
    reason_for_discontinuation_pd_1_toxicity_2_ongoing_response_3_death_4_other_5_explain == 2        ~ "Toxicity",
    reason_for_discontinuation_pd_1_toxicity_2_ongoing_response_3_death_4_other_5_explain == 3        ~ "Ongoing response",
    reason_for_discontinuation_pd_1_toxicity_2_ongoing_response_3_death_4_other_5_explain == 4        ~ "Death",
    reason_for_discontinuation_pd_1_toxicity_2_ongoing_response_3_death_4_other_5_explain == 5        ~ "Other",
    TRUE                                      ~ reason_for_discontinuation_pd_1_toxicity_2_ongoing_response_3_death_4_other_5_explain
  )) %>%



  mutate(cause_of_death_pd_1_infection_while_of_bs_ab_2_crs_3_icans_4_other_5_explain = case_when(
    cause_of_death_pd_1_infection_while_of_bs_ab_2_crs_3_icans_4_other_5_explain == 1        ~ "PD",
    cause_of_death_pd_1_infection_while_of_bs_ab_2_crs_3_icans_4_other_5_explain == 2        ~ "Infection",
    cause_of_death_pd_1_infection_while_of_bs_ab_2_crs_3_icans_4_other_5_explain == 3        ~ "CRS",
    cause_of_death_pd_1_infection_while_of_bs_ab_2_crs_3_icans_4_other_5_explain == 4        ~ "ICANS",
    cause_of_death_pd_1_infection_while_of_bs_ab_2_crs_3_icans_4_other_5_explain == 5        ~ "Others",
    TRUE                                      ~ as.character(cause_of_death_pd_1_infection_while_of_bs_ab_2_crs_3_icans_4_other_5_explain)
  )) %>%


  # mutate(time_from_tec_to_end_extraction_days =
  #          interval(start = date_of_bs_ab_step_up_d1, end = end_of_data_extraction) /
  #          duration(n =1, unit = "days")
  # )







table(cart5$progression_yes_no, cart5$pfs_event)
table(cart5$death_yes_no, cart5$os_event)
```


```{r response}
cart4 <- cart3 %>%   
  mutate(day30_response = case_when(
    (os_event == 1 | pfs_event == 1) &
      pfs_time_from_initiation_months < 1                               ~ "Died or progressed before day 30",
    str_detect(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd, "EVAL")        ~ NA_character_,
    day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd == "NE"                    ~ NA_character_,
    str_detect(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd, "VGPR")        ~ "VGPR",
    str_detect(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd, "PR")          ~ "PR",
    # str_detect(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd, "UCR")	       ~ "UCR",
    str_detect(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd, "CR")          ~ "sCR or CR",
    str_detect(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd, "MR") |
      str_detect(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd, "SD")        ~ "SD",
    str_detect(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd, "PD")          ~ "PD",
    is.na(day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd)                     ~ NA_character_,
    TRUE                                                                ~ day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd
  ), .after = day_30_response_s_cr_cr_vgpr_pr_mr_sd_pd) %>%
  mutate(day30_response_v2 = case_when(
    str_detect(day30_response, "Died")                               ~ "PD",
    is.na(day30_response)                                            ~ NA_character_,
    TRUE                                                             ~ day30_response
  ), .after = day30_response) %>%
  mutate(ORR_30days = case_when(
    str_detect(day30_response_v2, "CR|PR")                           ~ "PR or better",
    is.na(day30_response_v2)                                         ~ NA_character_,
    TRUE                                                             ~ "< PR"
  ), .after = day30_response_v2) %>%
  mutate(CRorbetter_30days = case_when(
    str_detect(day30_response_v2, "CR")	                             ~ "sCR or CR",
    is.na(day30_response_v2)                                         ~ NA_character_,
    TRUE                                                             ~ "< CR"
  ), .after = ORR_30days) %>%
  mutate(VGPRorbetter_30days = case_when(
    CRorbetter_30days == "sCR or CR"                        	       ~ "VGPR or better",
    day30_response_v2 == "VGPR"                        	             ~ "VGPR or better",
    is.na(day30_response_v2)                                         ~ NA_character_,
    TRUE                                                             ~ "< VGPR"
  ), .after = CRorbetter_30days) %>%
  # Day 90 response ----
  mutate(mon3_response = case_when(
    day30_response_v2 == "PD"                                         ~ "PD", #if was PD, is always PD
    (os_event == 1 | pfs_event == 1) &
      pfs_time_from_initiation_months < 3                             ~ "Died or progressed before 3 months",
    str_detect(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd, "EVAL")      ~ NA_character_,
    day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd == "NE"                  ~ NA_character_,
    str_detect(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd, "VGPR")      ~ "VGPR",
    str_detect(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd, "VPGR")      ~ "VGPR",
    str_detect(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd, "PR")        ~ "PR",
    str_detect(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd, "CR")	      ~ "sCR or CR",
    str_detect(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd, "MR") |
      str_detect(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd, "SD")      ~ "SD",
    str_detect(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd, "PD")        ~ "PD",
    is.na(day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd)                   ~ NA_character_,
    TRUE           ~ day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd
  ), .after = day_90_response_s_cr_cr_vgpr_pr_mr_sd_pd) %>%
  mutate(mon3_response_v2 = case_when(
    str_detect(mon3_response, "Died")                                 ~ "PD",
    is.na(mon3_response)                                              ~ NA_character_,
    TRUE                                                              ~ mon3_response
  ), .after = mon3_response) %>%
  mutate(ORR_mon3 = case_when(
    str_detect(mon3_response_v2, "CR|PR")                             ~ "PR or better",
    is.na(mon3_response_v2)                                           ~ NA_character_,
    TRUE                                                              ~ "< PR"
  ), .after = mon3_response_v2) %>%
  mutate(CRorbetter_mon3 = case_when(
    mon3_response_v2 == "sCR or CR"                        	          ~ "sCR or CR",
    is.na(mon3_response_v2)                                           ~ NA_character_,
    TRUE                                                              ~ "< CR"
  ), .after = ORR_mon3) %>%
  mutate(VGPRorbetter_mon3 = case_when(
    CRorbetter_mon3 == "sCR or CR"                        	          ~ "VGPR or better",
    mon3_response_v2 == "VGPR"                        	              ~ "VGPR or better",
    is.na(mon3_response_v2)                                           ~ NA_character_,
    TRUE                                                              ~ "< VGPR"
  ), .after = CRorbetter_mon3) %>%

    # Best response
  # mutate(ORR_as_best_response = case_when(
  #   ORR_30days == "PR or better" |
  #   ORR_mon3 == "PR or better" #|
  #   # ORR_mon6 == "ORR" |
  #   # ORR_mon9 == "ORR" |
  #   # ORR_mon12 == "ORR"
  #                                                                 ~ "PR or better",
  #   is.na(ORR_30days) &
  #     is.na(ORR_mon3) #&
  #     # is.na(ORR_mon6) &
  #     # is.na(ORR_mon9) &
  #     # is.na(ORR_mon12)
  #                                                                 ~ NA_character_,
  #    TRUE                                                         ~ "< PR"
  # ), .after = CRorbetter_mon3) %>%
  mutate(best_CRorbetter = case_when(
     CRorbetter_30days == "sCR or CR" |
       CRorbetter_mon3 == "sCR or CR" #|
       # CRorbetter_mon6 == "sCR or CR" |
       # CRorbetter_mon9 == "sCR or CR" |
       # CRorbetter_mon12 == "sCR or CR"
                                                                   ~ "sCR or CR",
     is.na(CRorbetter_30days) &
       is.na(CRorbetter_mon3) #&
       # is.na(CRorbetter_mon6) &
       # is.na(CRorbetter_mon9) &
       # is.na(CRorbetter_mon12)
                                                                   ~ NA_character_,
     TRUE                                                          ~ "< CR"
   ), .after = CRorbetter_mon3) %>%
  mutate(best_VGPRorbetter = case_when(
     VGPRorbetter_mon3 == "VGPR or better" |
       VGPRorbetter_30days == "VGPR or better"                     ~ "VGPR or better",
     is.na(VGPRorbetter_mon3) &
       is.na(VGPRorbetter_30days)                                  ~ NA_character_,
     TRUE                                                          ~ "< VGPR"
   ), .after = CRorbetter_mon3) %>%
  mutate(best_response = case_when(
    day30_response_v2 == "sCR or CR" |
      mon3_response_v2 == "sCR or CR" #|
      # mon6_response_v2 == "sCR or CR" |
      # mon9_response_v2 == "sCR or CR" |
      # mon12_response_v2 == "sCR or CR"
                                                                  ~ "sCR or CR",
    day30_response_v2 == "VGPR" |
      mon3_response_v2 == "VGPR" #|
      # mon6_response_v2 == "VGPR" |
      # mon9_response_v2 == "VGPR" |
      # mon12_response_v2 == "VGPR"
                                                                  ~ "VGPR",
    day30_response_v2 == "PR" |
      mon3_response_v2 == "PR" #|
      # mon6_response_v2 == "PR" |
      # mon9_response_v2 == "PR" |
      # mon12_response_v2 == "PR"
                                                                  ~ "PR",
    day30_response_v2 == "SD" |
      mon3_response_v2 == "SD" #|
      # mon6_response_v2 == "SD" |
      # mon9_response_v2 == "SD" |
      # mon12_response_v2 == "SD"
                                                                  ~ "SD",
    day30_response_v2 == "PD" |
      mon3_response_v2 == "PD" #|
      # mon6_response_v2 == "PD" |
      # mon9_response_v2 == "PD" |
      # mon12_response_v2 == "PD"
                                                                  ~ "PD",
    TRUE                                                          ~ NA_character_
  ), .after = best_CRorbetter) %>%
  mutate(best_ORRcollapsed = case_when(
    str_detect(best_response, "CR|PR")                            ~ "PR or better",
    str_detect(best_response, "SD|PD")                            ~ "< PR",
    TRUE                                                          ~ NA_character_
  ), .after = best_response) %>%
  mutate(best_response_s_cr_cr_vgpr_pr_mr_sd_pd = case_when(
    best_response_s_cr_cr_vgpr_pr_mr_sd_pd == "NE"                  ~ NA_character_,
    str_detect(best_response_s_cr_cr_vgpr_pr_mr_sd_pd, "VGPR")      ~ "VGPR",
    str_detect(best_response_s_cr_cr_vgpr_pr_mr_sd_pd, "VPGR")      ~ "VGPR",
    str_detect(best_response_s_cr_cr_vgpr_pr_mr_sd_pd, "PR")        ~ "PR",
    str_detect(best_response_s_cr_cr_vgpr_pr_mr_sd_pd, "CR")	      ~ "sCR or CR",
    str_detect(best_response_s_cr_cr_vgpr_pr_mr_sd_pd, "MR") |
      str_detect(best_response_s_cr_cr_vgpr_pr_mr_sd_pd, "SD")      ~ "SD",
    str_detect(best_response_s_cr_cr_vgpr_pr_mr_sd_pd, "PD")        ~ "PD",
    is.na(best_response_s_cr_cr_vgpr_pr_mr_sd_pd)                   ~ NA_character_,
    TRUE           ~ best_response_s_cr_cr_vgpr_pr_mr_sd_pd
  )) |> 
  # MRD----
  # mutate(across(c(contains("mrd_by_")),
  #           ~ case_when(
  #             . == "Positive"                                     ~ "Positive",
  #             . == "Negative"                                     ~ "Negative",
  #             TRUE                                                ~ NA_character_
  #           ))) %>%
  # mutate(MRD_day30 = coalesce(day_30_mrd_by_clono_seq_positive_vs_negative,
  #                              day_30_mrd_by_flow_positive_vs_negative
  # )) %>%
  # mutate(MRD_mon3 = coalesce(x3_month_mrd_by_clono_seq_positive_vs_negative,
  #                              x3_month_mrd_by_flow_positive_vs_negative
  # )) %>%
  # mutate(MRD_mon6 = coalesce(x6_month_mrd_by_clono_seq_positive_vs_negative,
  #                              x6_month_mrd_by_flow_positive_vs_negative
  # )) %>%
  # mutate(MRD_mon9 = coalesce(x9_month_mrd_by_clono_seq_positive_vs_negative,
  #                              x9_month_mrd_by_flow_positive_vs_negative
  # )) %>%
  # mutate(MRD_mon12 = coalesce(x12_month_mrd_by_clono_seq_positive_vs_negative,
  #                              x12_month_mrd_by_flow_positive_vs_negative
  # )) %>%
  # mutate(response_MRD_day30 = case_when(
  #   day30_response_v2 == "sCR or CR" &
  #     MRD_day30 == "Negative"                                     ~ "sCR or CR, MRD-",
  #   day30_response_v2 == "sCR or CR" &
  #     MRD_day30 == "Positive"                                     ~ "sCR or CR, MRD+",
  #   day30_response_v2 == "sCR or CR" &
  #     is.na(MRD_day30)                                            ~ "sCR or CR, MRD unknown",
  #   TRUE ~ day30_response_v2
  # )) %>%
  # mutate(response_MRD_mon3 = case_when(
  #   mon3_response_v2 == "sCR or CR" &
  #     MRD_mon3 == "Negative"                                      ~ "sCR or CR, MRD-",
  #   mon3_response_v2 == "sCR or CR" &
  #     MRD_mon3 == "Positive"                                      ~ "sCR or CR, MRD+",
  #   mon3_response_v2 == "sCR or CR" &
  #     is.na(MRD_mon3)                                             ~ "sCR or CR, MRD unknown",
  #   TRUE ~ mon3_response_v2
  # )) %>%
  # mutate(response_MRD_mon6 = case_when(
  #   mon6_response_v2 == "sCR or CR" &
  #     MRD_mon6 == "Negative"                                      ~ "sCR or CR, MRD-",
  #   mon6_response_v2 == "sCR or CR" &
  #     MRD_mon6 == "Positive"                                      ~ "sCR or CR, MRD+",
  #   mon6_response_v2 == "sCR or CR" &
  #     is.na(MRD_mon6)                                             ~ "sCR or CR, MRD unknown",
  #   TRUE ~ mon6_response_v2
  # )) %>%
  # mutate(response_MRD_mon9 = case_when(
  #   mon9_response_v2 == "sCR or CR" &
  #     MRD_mon9 == "Negative"                                      ~ "sCR or CR, MRD-",
  #   mon9_response_v2 == "sCR or CR" &
  #     MRD_mon9 == "Positive"                                      ~ "sCR or CR, MRD+",
  #   mon9_response_v2 == "sCR or CR" &
  #     is.na(MRD_mon9)                                             ~ "sCR or CR, MRD unknown",
  #   TRUE ~ mon9_response_v2
  # )) %>%
  # mutate(response_MRD_mon12 = case_when(
  #   mon12_response_v2 == "sCR or CR" &
  #     MRD_mon12 == "Negative"                                      ~ "sCR or CR, MRD-",
  #   mon12_response_v2 == "sCR or CR" &
  #     MRD_mon12 == "Positive"                                      ~ "sCR or CR, MRD+",
  #   mon12_response_v2 == "sCR or CR" &
  #     is.na(MRD_mon12)                                             ~ "sCR or CR, MRD unknown",
  #   TRUE ~ mon12_response_v2
  # )) %>%
  mutate(best_MRD_response = case_when(
    # prioritize clonoseq and then use flow
    best_response_mrd_clonoseq_positive_vs_negative == "Positive"  ~ "MRD+",
    best_response_mrd_clonoseq_positive_vs_negative == "Negative"  ~ "MRD-",
    best_response_mrd_flow_positive_vs_negative == "Positive"      ~ "MRD+",
    best_response_mrd_flow_positive_vs_negative == "Negative"      ~ "MRD-",
    !is.na(best_CRorbetter)                                        ~ "MRD unknown"
  )) %>%
  mutate(best_response_CR_MRD = case_when(
    best_CRorbetter == "sCR or CR"
    ~ paste0(best_CRorbetter, ", ", best_MRD_response),
    best_CRorbetter == "< CR"                                      ~ best_response
  ))
  # mutate(best_response_MRD = case_when (
  #   response_MRD_day30 == "sCR or CR, MRD-" |
  #     response_MRD_mon3 == "sCR or CR, MRD-" |
  #     response_MRD_mon6 == "sCR or CR, MRD-" |
  #     response_MRD_mon9 == "sCR or CR, MRD-" |
  #     response_MRD_mon12 == "sCR or CR, MRD-"                      ~ "sCR or CR, MRD-",
  #    response_MRD_day30 == "sCR or CR, MRD+" |
  #     response_MRD_mon3 == "sCR or CR, MRD+" |
  #     response_MRD_mon6 == "sCR or CR, MRD+" |
  #     response_MRD_mon9 == "sCR or CR, MRD+" |
  #     response_MRD_mon12 == "sCR or CR, MRD+"                      ~ "sCR or CR, MRD+",
  #    response_MRD_day30 == "sCR or CR, MRD unknown" |
  #     response_MRD_mon3 == "sCR or CR, MRD unknown" |
  #     response_MRD_mon6 == "sCR or CR, MRD unknown" |
  #     response_MRD_mon9 == "sCR or CR, MRD unknown" |
  #     response_MRD_mon12 == "sCR or CR, MRD unknown"               ~ "sCR or CR, MRD unknown",
  #   TRUE ~ best_response
  # )) %>%
  # mutate(MRDneg_in_best_response = case_when(
  #   MRD_day30 ==  "Negative" |
  #     MRD_mon3 ==  "Negative" |
  #     MRD_mon6 ==  "Negative" |
  #     MRD_mon9 ==  "Negative" |
  #     MRD_mon12 ==  "Negative"                                    ~ "Negative",
  #   MRD_day30 ==  "Positive" |
  #   MRD_mon3 ==  "Positive" |
  #   MRD_mon6 ==  "Positive" |
  #   MRD_mon9 ==  "Positive" |
  #     MRD_mon12 ==  "Positive"                                    ~ "Positive",
#   TRUE                                                          ~ NA_character_
# )) %>%
  # mutate(bridging_response = case_when(
  #   response_to_bridging_chemotherapy == "MR" |
  #     response_to_bridging_chemotherapy == "SD/MR" |
  #     response_to_bridging_chemotherapy == "SD" |
  #     response_to_bridging_chemotherapy == "PD" |
  #     response_to_bridging_chemotherapy == "No"               ~ "SD/PD",
  #   response_to_bridging_chemotherapy == "CR" |
  #     response_to_bridging_chemotherapy == "PR" |
  #     response_to_bridging_chemotherapy == "VGPR"             ~ "PR or better",
  #   response_to_bridging_chemotherapy == "Not Evaluable" |
  #     response_to_bridging_chemotherapy == "ND" |
  #     response_to_bridging_chemotherapy == "Unknown"          ~ NA_character_,
  #   TRUE                                                      ~ NA_character_
  # ))
```

```{r cytopenia}
cart2 <- cart2 #%>% 
  # # Any cytopenia (ANC<1500, WBC < 4, Hb <12 or Plt < 150)
  # mutate(cytopenia_baseline = case_when(
  #   baseline_anc_k_u_l_ie_100_200_etc < 1.8 | 
  #     baseline_hgb < 11.4 | 
  #     baseline_pl_ts < 143                                             ~ "Yes",
  #   # if any is NA, we cannot truly code as No so NA
  #   is.na(baseline_anc_k_u_l_ie_100_200_etc) |
  #     is.na(baseline_hgb) |
  #     is.na(baseline_pl_ts)                                            ~ NA_character_,
  #   TRUE                                                              ~ "No"
  # )) %>% 
  # # Grade 3+ cytopenia (ANC<1000, Hb<8 or Plt<50) at day 30
  # mutate(gr3_cytopenia_baseline = case_when(
  #   baseline_anc_k_u_l_ie_100_200_etc < 1 | 
  #     baseline_hgb < 8 | 
  #     baseline_pl_ts < 50                                             ~ "Yes",
  #   is.na(baseline_anc_k_u_l_ie_100_200_etc) |
  #     is.na(baseline_hgb) |
  #     is.na(baseline_pl_ts)                                            ~ NA_character_,
  #   TRUE                                                              ~ "No"
  # ))
```





```{r infection}
bsab_data <- cart4 %>%
  # Infection
  mutate(infection_severity_2 = case_when(
    date_of_infection_2 == date_of_bs_ab_step_up_d1     ~ infection_severity_3,
    TRUE                                     ~ infection_severity_2
  )) |> 
  mutate(infection_type_2 = case_when(
    date_of_infection_2 == date_of_bs_ab_step_up_d1     ~ infection_type_3,
    TRUE                                     ~ infection_type_2
  )) |> 
  mutate(date_of_infection_2 = case_when(
    date_of_infection_2 == date_of_bs_ab_step_up_d1     ~ date_of_infection_3,
    TRUE                                     ~ date_of_infection_2
  )) |> 
  mutate(infection_severity_1 = case_when(
    date_of_infection_1 == date_of_bs_ab_step_up_d1     ~ infection_severity_2,
    TRUE                                     ~ infection_severity_1
  )) |> 
  mutate(infection_type_1 = case_when(
    date_of_infection_1 == date_of_bs_ab_step_up_d1     ~ infection_type_2,
    TRUE                                     ~ infection_type_1
  )) |> 
  mutate(date_of_infection_1 = case_when(
    date_of_infection_1 == date_of_bs_ab_step_up_d1     ~ date_of_infection_2,
    TRUE                                     ~ date_of_infection_1
  )) |> 
  mutate(time_from_bsab_therapy_to_1st_infection_days = 
           interval(
             start = date_of_bs_ab_step_up_d1, 
             end = date_of_infection_1)/
           duration(n=1, units = "days"),
     .after = date_of_infection_1) %>%
  mutate(time_from_bsab_therapy_to_1st_infection_months = 
           interval(
             start = date_of_bs_ab_step_up_d1, 
             end = date_of_infection_1)/
           duration(n=1, units = "months"),
     .after = date_of_infection_1)
  mutate(infection_n_0_y_1 = case_when(
    if_any(any_of(contains("infection_type")), ~ !is.na(.)) ~ "Yes",
    TRUE                                                    ~ infection_n_0_y_1
  ))
  # mutate(any_infection = case_when(
  #   time_from_bsab_therapy_to_1st_infection_days >= 0     ~ infection_yes_1_no_0,
  #   TRUE                                          ~ "No"
  # )) %>%
  # mutate(any_sevinfection = case_when(
  #   time_from_bsab_therapy_to_1st_infection_days >= 0     ~ severe_infection_need_for_iv_antibiotics_and_or_hospitalization_yes_1_no_0,
  #   TRUE                                          ~ "No"
  # )) %>% 
  # mutate(across(c("infection_type_details", "infection_type_bacterial_viral_fungal_parasitic",
  #                 "infection_type_cat"), ~ case_when(
  #   time_from_bsab_therapy_to_1st_infection_days >= 0     ~ .,
  #   TRUE                                          ~ NA_character_
  # ))) %>% 
  # mutate(overall_hlh = case_when(
  #   hlh == "Yes" |
  #   hlh_hlh_like_toxicities == "Yes"              ~ "Yes",
  #   hlh == "No" &
  #   hlh_hlh_like_toxicities == "No"               ~ "No"
  # ))
  

# cart7 <- cart6 %>% 
#   mutate(infection = case_when(
#     notinfused=="YES" ~ NA_character_,
#     notinfused=="NO" & is.na(`Infection Type`) & is.na(`Infection (Yes, No)`) ~ NA_character_,
#     notinfused=="NO" & `Infection Type` == "No" ~ "No", 
#     notinfused=="NO" & `Infection Type` != "No" ~ "Yes",
#     notinfused=="NO" & is.na(`Infection Type`) ~ "No",
#     TRUE ~ NA_character_
#   )) %>%
#   mutate(infection_type = case_when(
#     infection=="No" | is.na(infection) ~ NA_character_,
#     infection=="Yes" & `Infection Details (specific infection, ie. E.coli bacteremia, etc.)` == "fungus was unidentified" ~ "Fungal",
#     infection== "Yes" & `Infection Details (specific infection, ie. E.coli bacteremia, etc.)` == "E. coli bacteremia and Salmonella GI infection treated with ceftriaxone x 7 days" ~ "Bacterial",
#     infection=="Yes" & `Infection Type`=="bacterial + viral" ~ "Bacterial + Viral",
#     infection=="Yes" & `Infection Type`=="viral" ~ "Viral",
#     infection=="Yes" & `Infection Type`=="All of the above" ~ "Bacterial, Viral, and Fungal",
#     infection=="Yes" & `Infection Type`=="Bacterial; Viral; Bacterial" ~ "Bacterial + Viral",
#     infection=="Yes" & `Infection Type`=="Viral; Bacterial; Bacterial" ~ "Bacterial + Viral",
#     TRUE ~ `Infection Type`
#   )) %>% 
#   mutate(infection_severity = case_when(
#      infection=="No" | is.na(infection) ~ NA_character_,
#      infection=="Yes" & is.na(`Infection Severity (Severe = hospitalization or requiring IV antibiotics)`) ~ NA_character_,
#      infection=="Yes" & `Infection Severity (Severe = hospitalization or requiring IV antibiotics)`=="severe" ~ "Severe",
#      infection=="Yes" & `Infection Severity (Severe = hospitalization or requiring IV antibiotics)`=="Yes" ~ "Severe",
#      infection=="Yes" & `Infection Severity (Severe = hospitalization or requiring IV antibiotics)`=="non-severe" ~ "Not severe",
#     infection=="Yes" & `Infection Severity (Severe = hospitalization or requiring IV antibiotics)`=="Non-Severe" ~ "Not severe",
#     TRUE ~ `Infection Severity (Severe = hospitalization or requiring IV antibiotics)`
#   )) %>%
#   mutate(infection_type = factor(infection_type, levels = c("Bacterial", "Fungal", "Viral", "Bacterial + Fungal", "Bacterial + Viral", "Bacterial, Viral, and Fungal")))
```
